//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWBTaskDAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RWBTaskEntitiesConnection : DbContext
    {
        public RWBTaskEntitiesConnection()
            : base("name=RWBTaskEntitiesConnection")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<vwEventInformation> vwEventInformations { get; set; }
        public DbSet<vwEventMarketLine> vwEventMarketLines { get; set; }
    }
}
