//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWBTaskDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEventMarketLine
    {
        public long Id { get; set; }
        public long EventId { get; set; }
        public string MarketName { get; set; }
        public bool IsLive { get; set; }
        public string LineName { get; set; }
        public decimal Price { get; set; }
        public long LineId { get; set; }
    }
}
