//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RWBTaskDAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwEventInformation
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public System.DateTime StartTime { get; set; }
        public string LeagueName { get; set; }
        public string CategoryName { get; set; }
        public long LeagueId { get; set; }
        public long SportId { get; set; }
        public long CategoryId { get; set; }
        public string SportName { get; set; }
    }
}
